# Numpy & Pandas
In this notebook, we'll encounter two packages for scientific computing in Python: NumPy and Pandas.

**At the end of this notebook, you'll be able to:**
* Install and import packages for Python
* Create NumPy arrays
* Execute methods & access attributes of arrays
* Create & manipulate Pandas dataframes


## Importing packages

Before we can use numpy or pandas, we need to import them. We can also nickname the modules when we import them.

The convention is to import `numpy` as `np` and `pandas` as `pd`.

In [ ]:
# Import packages
import numpy as np
import pandas as pd

# Use whos 'magic command' to see available modules
%whos

## Numpy

**Numpy** is the fundamental package for scientific computing with Python. It'll allow us to work with bigger datasets more efficiently.

### Creating `numpy` arrays

A numpy **array** is a grid of values which are all the same type (they’re homogenous).

We can create a numpy array in a few different ways:

* from a Python list or tuples
* by using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, `empty`,`zeroes`, etc.
* reading data from files

In [ ]:
# Create a list
lst = [1,2,3,4,5]

# Make our list into an array
my_vector = np.array(lst)
type(my_vector)

In [ ]:
# If we give numpy a list of lists, it will create a matrix
my_matrix = np.array([lst,lst])

### Accessing attributes of numpy arrays
We can test shape and size either by looking at the attribute of the array, or by using the `shape()` and `size()` functions.

Other attributes that might be of interest are `ndim` and `dtype`.

In [ ]:
# Check the dimensions of vector
my_vector.ndim

# Check the dimensions of matrix
my_matrix.ndim

Array data type is decided upon creation of the array.

You can explicitly define the data type by using `dtype= ` when you use `np.array()`. You can set the dtype to be `int, float, complex, bool, object`, etc

In [ ]:
my_array.dtype 

# my_complex_array = np.array([lst,lst],dtype='complex')
# my_complex_array

<div class="alert alert-success">

**Task**: Create an array of booleans called `bool_array` that is 2 rows x 3 columns. Access the `shape` and `ndim` attributes to confirm its size, and the `dtype` attribute to confirm that it is boolean.

</div>

In [ ]:
bool_array = 

### Indexing Arrays

Indexing 1D arrays (vectors) is similar to indexing lists.

You can index matrices using `[row,column]`. If you omit the column, it will give you the whole row.

If you use `:` for either row or column, it will give you all of those values.

In [ ]:
my_matrix[:,0]

We can also index arrays using booleans or lists. For example:

In [ ]:
# Index with an operator
bool_matrix = my_matrix[my_matrix>2]

# Index with a list of coordinates
list_matrix = my_matrix[[0,1],[1,3]]

print(my_matrix)
print(bool_matrix)
print(list_matrix)

<div class="alert alert-success">

**Task**: Filter the `bool_array` you created above to create a `true_array` that only contains True values.

</div>

We can also change values in an array similar to how we would change values in a list.

In [ ]:
print(my_matrix)
my_matrix[0] = 8
print(my_matrix)

### Benefits of using arrays
In addition to being less clunky & a bit faster than lists of lists, arrays can do a lot of things that lists can't. For example, we can add and multiply them. Alternatively, we can use the `sum` method to sum across a specific axis.

In [ ]:
sum_list = [1,3,5] + [3,5,7]
sum_array = np.array([1,3,5]) + np.array([3,5,7])

print(sum_list)
print(sum_array)

In [73]:
this_array = np.array([[1,3,5],[3,5,7]])
sum_rows = this_array.sum(axis=0)
print(this_array)
print(sum_rows)

[[1 3 5]
 [3 5 7]]
[ 4  8 12]


### Numpy also includes some very useful array generating functions:

* `arange`: like `range` but gives you a useful numpy array, instead of an interator, and can use more than just integers)
* `linspace` creates an array with given start and end points, and a desired number of points
* `logspace` same as linspace, but in log.
* `random` can create a random list (there are <a href="https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html">many different ways to use this</a>)
* `concatenate` which can concatenate two arrays along an existing axis [<a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html">documentation</a>]
* `hstack` and `vstack` which can horizontally or vertically stack arrays

Whenever we call these, we need to use whatever name we imported numpy as (here, `np`).

In [ ]:
# When using linspace, both end points are included!
np.linspace(0,147,10)

<div class="alert alert-success">

**Task**: Create an array called `big_array` that has two rows. The first row should be a list of 10 numbers that are evenly spaced, and range from exactly 1 to 100. The second row should be a list of 10 numbers that begin at 0 and are exactly 10 apart. `big_array` should have a shape (2,10): two rows, and ten columns. Lastly, reassign the last value of each row in the array to be -100. 

*Hint*: Create your two arrays, and then use the `vstack` method to stack them.

</div>

Numpy also has built in methods to save and load dataframes: `np.save()` and `np.load()`. Numpy files have a .npy extension.

See full documentation <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.save.html">here</a>.

In [ ]:
# Save method takes arguments 'filename' and then 'array':
np.save('matrix',my_matrix)

In [ ]:
np.load('matrix.npy')

# Pandas

Pandas is a useful module that creates **data frames** (think of these like Excel spreadsheets, but much faster!). 

We can think of Pandas as "numpy with labels".


### Benefits of Pandas
* Great for real-world, heterogeneous data
* Similar to Excel spreadsheets (but way faster!)
* Smartly deals with missing data

We can work with the gene expression data from a2 as a Pandas dataframe!


In [98]:
# Import necessary packages
from csv import reader
import pandas as pd

# Read in the list of lists as a data frame
gene_df = pd.read_csv('brainarea_vs_genes_exp_w_reannotations.tsv',sep='\t',index_col = 'gene_symbol')
gene_df.head() # Show the first five rows

CA1 field  CA2 field  CA3 field  CA4 field  \
gene_symbol                                               
A1BG          0.856487  -1.773695  -0.678679  -0.986914   
A1BG-AS1      0.257664  -1.373085  -0.619923  -0.636275   
A1CF         -0.089614  -0.546903   0.282914  -0.528926   
A2M           0.552415  -0.635485  -0.954995  -0.259745   
A2ML1         0.758031   1.549857   1.262225   1.338780   

             Crus I, lateral hemisphere  Crus I, paravermis  \
gene_symbol                                                   
A1BG                           0.826986            0.948039   
A1BG-AS1                       0.362799            0.353296   
A1CF                           0.507916            0.577696   
A2M                           -1.687391           -1.756847   
A2ML1                         -0.289888           -0.407026   

             Crus II, lateral hemisphere  Crus II, paravermis  \
gene_symbol                                                     
A1BG                            0.935427             1.120774   
A1BG-AS1                        0.422766             0.346853   
A1CF                            0.647671             0.306824   
A2M                            -1.640242            -1.733110   
A2ML1                          -0.358798            -0.589988   

             Edinger-Westphal nucleus  Heschl's gyrus      ...       \
gene_symbol                                                ...        
A1BG                        -1.018554        0.170282      ...        
A1BG-AS1                    -0.812015        0.903358      ...        
A1CF                         0.089958        0.149820      ...        
A2M                         -0.091695        0.003428      ...        
A2ML1                        0.944684       -0.466327      ...        

             temporal pole, inferior aspect  temporal pole, medial aspect  \
gene_symbol                                                                 
A1BG                               0.277830                      0.514923   
A1BG-AS1                           1.074116                      0.821031   
A1CF                              -0.030265                     -0.187367   
A2M                               -0.058505                      0.207109   
A2ML1                             -0.472908                     -0.598317   

             temporal pole, superior aspect  transverse gyri  \
gene_symbol                                                    
A1BG                               0.733368        -0.104286   
A1BG-AS1                           1.219272         0.901213   
A1CF                              -0.428358        -0.465863   
A2M                               -0.161808         0.183630   
A2ML1                             -0.247797        -0.282673   

             trochlear nucleus  tuberomammillary nucleus  \
gene_symbol                                                
A1BG                 -0.910245                  1.039610   
A1BG-AS1             -1.522431                  0.598719   
A1CF                 -0.136936                  1.229487   
A2M                   0.948098                 -0.977692   
A2ML1                 1.396365                  0.945043   

             ventral tegmental area  ventromedial hypothalamic nucleus  \
gene_symbol                                                              
A1BG                      -0.155167                          -0.444398   
A1BG-AS1                  -1.709745                          -0.054156   
A1CF                      -0.110680                          -0.118175   
A2M                        0.911896                          -0.499357   
A2ML1                      0.158202                           0.572771   

             vestibular nuclei  zona incerta  
gene_symbol                                   
A1BG                 -0.901361     -0.236790  
A1BG-AS1             -1.695843     -1.155961  
A1CF                 -0.139776      0.123829  
A2M                   1.469386      0.5

Indexing in Pandas  works slightly different. Similar to a dictionary, we can index values by their names.

* Use `df['index']` for columns, and method `.loc` for rows.
* Use `.iloc` to index by #.

In [106]:
DISC1_data = gene_df.loc['DISC1']
DISC1_data['CA4 field']

0.3775630586767744

Pandas has many, many useful methods that you can use on your data, including `describe`, `mean`, and more.

In [103]:
DISC1_data.describe()

count    232.000000
mean      -0.006324
std        0.965280
min       -1.572527
25%       -0.715778
50%       -0.132084
75%        0.831907
max        2.173866
Name: DISC1, dtype: float64

## Resources
Check out the <a href="https://docs.scipy.org/doc/numpy/user/index.html">NumPy user guide</a> if you ever have a question about a NumPy array!

## About this notebook
This notebook is largely derived from UCSD COGS18 Materials, created by Tom Donoghue & Shannon Ellis, as well as <a href="https://github.com/jrjohansson/scientific-python-lectures/blob/master/Lecture-2-Numpy.ipynb">JR Johannson's Scientific Python Lecture on Numpy</a>.


Want to run this notebook as a slideshow? If you have Python (or Anaconda) follow <a href="http://www.blog.pythonlibrary.org/2018/09/25/creating-presentations-with-jupyter-notebook/">these instructions</a> to setup your computer with the RISE plugin.